packages:
  - "diagram-as-code"
  - "microfrontend"
  - "vim-rabbit-hole"
  - "why-no-microfrontend"
  - "typescript-is-fun"
catalogs:
  prettier:
    "prettier": "^3.7.4"
    "prettier-plugin-slidev": "^1.0.5"
